### ISSUE TITLE
Bug 🐛 : Application is not working .

### ISSUE THREAD

**Issue by aryasoni98** [ScanRE/ScanRE#1]
1: Where is some network error.
2: In the `backend folder` Step 3 not working. This command: `celery -A app.routes.celery worker --loglevel=info -P gevent`

![Screenshot 2023-06-24 at 3 50 57 AM](https://github.com/ScanRE/ScanRE/assets/18515597/4756e403-5a4d-411b-9635-b7ab653ff3e0)

<img width="525" alt="Screenshot 2023-06-24 at 3 50 19 AM" src="https://github.com/ScanRE/ScanRE/assets/18515597/8f62eac1-3514-4288-aa5a-fe7429185d88">

**Comment by JadenFurtado** [comment]
## Yup. That's because we commented out the Celery part of the code for the purpose of the demonstration during the hackathon :innocent:!

_The reason? We didn't want unnecessary complexity during a demo! You have 2 possible fixes for this._ 

You could

* Uncomment the section in mh-backend/app/routes.py and add the CELERY_BROKER_URL to the app config
```
#logger = get_task_logger(__name__)

#app = Flask(__name__)

#celery = Celery(app.name, broker=app.config["CELERY_BROKER_URL"])
#celery.conf.update(app.config)

#@celery.task()
```

or

* Just run the application without Celery. See https://github.com/ScanRE/ScanRE/blob/main/mh-backend/start.sh

## You should note that to truly get the best out of celery, you would need to add something like the piece of code shown below to the mh-backend/app/routes.py file:

```
@celery.task()
def scan(repositoryLink,path,repositoryName,finalOutput,multipleDirectories=0):
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        scanObj = CodeScanner(repositoryLink,path,repositoryName,finalOutput)
        loop.run_until_complete(scanObj.getCode())
        loop.run_until_complete(scanObj.scanCode())
        return json.load(open(finalOutput+"/"+repositoryName+".json","r"))
```

### I'll update the documentation and add this in there. You could open a PR for this if you feel like it :)
